/**
 * Wortschatz-Daten für die App „Wort & Bedeutung“ (idee-db: 37).
 *
 * 300 Begriffe aus 10 Gebieten, von gegenständlich (Stufe 1) bis bildhaft
 * (Stufe 5). Jeder Eintrag:
 *   [Wort de, Wort ru, Wort en, Bedeutung de, Bedeutung ru, Bedeutung en,
 *    Kategorie, Stufe, (optional) Bild-Pfad]
 *
 * Bilder: Feld 9 (optional) kann später auf `bilder/<datei>.png` zeigen.
 * Solange kein Bild hinterlegt ist, zeichnet die App einen Platzhalter
 * (Rechteck mit dem Wort) – die Bilder lassen sich anhand dieser
 * Platzhalter nachträglich erstellen.
 */

export const BEGRIFFE = [
  // ── Natur ──────────────────────────────────────────────────────────
  ["Baum", "Дерево", "tree", "Pflanze mit Stamm und Blättern", "Растение со стволом и листьями", "A plant with a trunk and leaves", "natur", 1],
  ["Blume", "Цветок", "flower", "bunte Pflanze, die blüht", "яркое растение, которое цветёт", "A colourful plant that blooms", "natur", 1],
  ["Gras", "Трава", "grass", "kleine grüne Pflanze am Boden", "маленькое зелёное растение на земле", "A small green plant on the ground", "natur", 1],
  ["Stein", "Камень", "stone", "harter Brocken aus der Erde", "твёрдый кусок из земли", "A hard piece of rock", "natur", 1],
  ["Berg", "Гора", "mountain", "sehr großer Hügel aus Fels", "очень большой холм из скал", "A very large rocky hill", "natur", 1],
  ["Fluss", "Река", "river", "großes fließendes Wasser", "большая текущая вода", "Large flowing water", "natur", 1],
  ["See", "Озеро", "lake", "großes stilles Wasser", "большой спокойный водоём", "A large still water", "natur", 1],
  ["Meer", "Море", "sea", "riesiges salziges Wasser", "огромная солёная вода", "Huge salty water", "natur", 1],
  ["Wald", "Лес", "forest", "viele Bäume zusammen", "много деревьев вместе", "Many trees together", "natur", 1],
  ["Wiese", "Луг", "meadow", "Fläche mit Gras und Blumen", "поляна с травой и цветами", "An area with grass and flowers", "natur", 1],
  ["Sonne", "Солнце", "sun", "heller Stern am Himmel, gibt Wärme", "яркая звезда на небе, даёт тепло", "A bright star in the sky, gives warmth", "natur", 1],
  ["Mond", "Луна", "moon", "heller Kreis am Nachthimmel", "светлый круг на ночном небе", "A bright circle in the night sky", "natur", 1],
  ["Stern", "Звезда", "star", "leuchtender Punkt am Nachthimmel", "светящаяся точка на ночном небе", "A shining dot in the night sky", "natur", 1],
  ["Wolke", "Облако", "cloud", "weiße Gebilde am Himmel", "белые образования на небе", "White shapes in the sky", "natur", 1],
  ["Regen", "Дождь", "rain", "Wasser, das vom Himmel fällt", "вода, падающая с неба", "Water falling from the sky", "natur", 1],
  ["Schnee", "Снег", "snow", "gefrorenes Wasser, das fällt", "замёрзшая вода, которая падает", "Frozen water that falls", "natur", 1],
  ["Wind", "Ветер", "wind", "bewegte Luft", "движущийся воздух", "Moving air", "natur", 1],
  ["Blitz", "Молния", "lightning", "helles Licht bei Gewitter", "яркий свет во время грозы", "A bright light during a storm", "natur", 1],
  ["Donner", "Гром", "thunder", "lautes Geräusch bei Gewitter", "громкий звук во время грозы", "A loud sound during a storm", "natur", 1],
  ["Erde", "Земля", "ground", "Boden, auf dem wir stehen", "почва, на которой мы стоим", "The ground we stand on", "natur", 1],
  ["Sand", "Песок", "sand", "feine Körner am Strand", "мелкие крупинки на пляже", "Fine grains on the beach", "natur", 1],
  ["Insel", "Остров", "island", "Land, das von Wasser umgeben ist", "суша, окружённая водой", "Land surrounded by water", "natur", 2],
  ["Wüste", "Пустыня", "desert", "sehr trockenes Gebiet mit Sand", "очень сухая местность с песком", "A very dry area with sand", "natur", 2],
  ["Tal", "Долина", "valley", "flaches Land zwischen Bergen", "ровная земля между горами", "Flat land between mountains", "natur", 2],
  ["Wasserfall", "Водопад", "waterfall", "Wasser, das einen Felsen hinunterstürzt", "вода, падающая со скалы", "Water falling down a rock", "natur", 2],
  ["Quelle", "Источник", "spring", "Ort, wo Wasser aus der Erde kommt", "место, где вода выходит из земли", "A place where water comes out of the ground", "natur", 2],
  ["Ufer", "Берег", "shore", "Rand von Fluss oder See", "край реки или озера", "The edge of a river or lake", "natur", 2],
  ["Hügel", "Холм", "hill", "kleiner Berg", "маленькая гора", "A small mountain", "natur", 2],
  ["Höhle", "Пещера", "cave", "Loch im Felsen oder Berg", "отверстие в скале или горе", "A hole in a rock or mountain", "natur", 2],
  ["Gipfel", "Вершина", "summit", "oberster Punkt eines Berges", "самая верхняя точка горы", "The highest point of a mountain", "natur", 2],

  // ── Tiere ──────────────────────────────────────────────────────────
  ["Hund", "Собака", "dog", "Haustier, das bellt", "домашнее животное, которое лает", "A pet that barks", "tiere", 1],
  ["Katze", "Кошка", "cat", "Haustier, das miaut", "домашнее животное, которое мяукает", "A pet that meows", "tiere", 1],
  ["Vogel", "Птица", "bird", "Tier mit Federn, das fliegt", "животное с перьями, которое летает", "An animal with feathers that flies", "tiere", 1],
  ["Fisch", "Рыба", "fish", "Tier, das im Wasser schwimmt", "животное, которое плавает в воде", "An animal that swims in water", "tiere", 1],
  ["Pferd", "Лошадь", "horse", "großes Tier, auf dem man reiten kann", "большое животное, на котором можно ездить верхом", "A big animal you can ride", "tiere", 1],
  ["Kuh", "Корова", "cow", "Tier, das Milch gibt", "животное, которое даёт молоко", "An animal that gives milk", "tiere", 1],
  ["Schwein", "Свинья", "pig", "Tier mit ringelndem Schwanz, grunzt", "животное с хвостиком крючком, хрюкает", "An animal with a curly tail, grunts", "tiere", 1],
  ["Schaf", "Овца", "sheep", "Tier mit Wolle", "животное с шерстью", "An animal with wool", "tiere", 1],
  ["Huhn", "Курица", "chicken", "Vogel, der Eier legt", "птица, которая несёт яйца", "A bird that lays eggs", "tiere", 1],
  ["Maus", "Мышь", "mouse", "kleines graues Nagetier", "маленький серый грызун", "A small grey rodent", "tiere", 1],
  ["Löwe", "Лев", "lion", "große Raubkatze mit Mähne", "большая хищная кошка с гривой", "A big wild cat with a mane", "tiere", 2],
  ["Elefant", "Слон", "elephant", "riesiges Tier mit Rüssel", "огромное животное с хоботом", "A huge animal with a trunk", "tiere", 2],
  ["Giraffe", "Жираф", "giraffe", "Tier mit sehr langem Hals", "животное с очень длинной шеей", "An animal with a very long neck", "tiere", 2],
  ["Affe", "Обезьяна", "monkey", "Tier, das gut klettert", "животное, которое хорошо лазает", "An animal that climbs well", "tiere", 2],
  ["Bär", "Медведь", "bear", "großes Tier mit dickem Fell", "большое животное с густой шерстью", "A big animal with thick fur", "tiere", 2],
  ["Wolf", "Волк", "wolf", "wildes Tier, das heult", "дикое животное, которое воет", "A wild animal that howls", "tiere", 2],
  ["Fuchs", "Лиса", "fox", "schlaues Tier mit rotem Fell", "хитрое животное с рыжим мехом", "A clever animal with red fur", "tiere", 2],
  ["Hase", "Заяц", "hare", "Tier mit langen Ohren, hoppelt", "животное с длинными ушами, прыгает", "An animal with long ears, hops", "tiere", 2],
  ["Igel", "Ёж", "hedgehog", "kleines Tier mit Stacheln", "маленькое животное с иголками", "A small animal with spines", "tiere", 2],
  ["Eule", "Сова", "owl", "Vogel, der nachts wach ist", "птица, которая бодрствует ночью", "A bird that is awake at night", "tiere", 2],
  ["Schmetterling", "Бабочка", "butterfly", "Insekt mit bunten Flügeln", "насекомое с разноцветными крыльями", "An insect with colourful wings", "tiere", 2],
  ["Biene", "Пчела", "bee", "Insekt, das Honig macht", "насекомое, которое делает мёд", "An insect that makes honey", "tiere", 2],
  ["Ameise", "Муравей", "ant", "sehr kleines fleißiges Insekt", "очень маленькое трудолюбивое насекомое", "A very small hardworking insect", "tiere", 2],
  ["Spinne", "Паук", "spider", "Tier mit acht Beinen, webt Netze", "животное с восемью ногами, плетёт сети", "An animal with eight legs, weaves webs", "tiere", 2],
  ["Schlange", "Змея", "snake", "Tier ohne Beine, kriecht", "животное без ног, ползает", "An animal without legs, crawls", "tiere", 2],
  ["Wal", "Кит", "whale", "riesiges Tier im Meer", "огромное животное в море", "A huge animal in the sea", "tiere", 2],
  ["Delfin", "Дельфин", "dolphin", "kluges Meeressäugetier", "умное морское млекопитающее", "A clever sea mammal", "tiere", 2],
  ["Pinguin", "Пингвин", "penguin", "Vogel, der schwimmt statt fliegt", "птица, которая плавает вместо полёта", "A bird that swims instead of flying", "tiere", 2],
  ["Frosch", "Лягушка", "frog", "Tier, das springt und quakt", "животное, которое прыгает и квакает", "An animal that jumps and croaks", "tiere", 2],
  ["Schildkröte", "Черепаха", "turtle", "Tier mit hartem Panzer", "животное с твёрдым панцирем", "An animal with a hard shell", "tiere", 2],

  // ── Körper ─────────────────────────────────────────────────────────
  ["Kopf", "Голова", "head", "oberster Teil des Körpers", "верхняя часть тела", "The top part of the body", "koerper", 1],
  ["Auge", "Глаз", "eye", "damit sehen wir", "им мы видим", "We see with it", "koerper", 1],
  ["Ohr", "Ухо", "ear", "damit hören wir", "им мы слышим", "We hear with it", "koerper", 1],
  ["Nase", "Нос", "nose", "damit riechen wir", "им мы нюхаем", "We smell with it", "koerper", 1],
  ["Mund", "Рот", "mouth", "damit essen und sprechen wir", "им мы едим и говорим", "We eat and speak with it", "koerper", 1],
  ["Hand", "Рука", "hand", "damit greifen wir", "ей мы хватаем", "We grab with it", "koerper", 1],
  ["Fuß", "Ступня", "foot", "damit gehen wir", "ей мы ходим", "We walk with it", "koerper", 1],
  ["Bein", "Нога", "leg", "Körperteil zum Stehen und Gehen", "часть тела для стояния и ходьбы", "A body part for standing and walking", "koerper", 1],
  ["Arm", "Рука", "arm", "Körperteil zwischen Schulter und Hand", "часть тела между плечом и кистью", "A body part between shoulder and hand", "koerper", 1],
  ["Finger", "Палец", "finger", "Teil der Hand", "часть руки", "A part of the hand", "koerper", 1],
  ["Haar", "Волосы", "hair", "wächst auf dem Kopf", "растёт на голове", "Grows on the head", "koerper", 1],
  ["Zahn", "Зуб", "tooth", "hart, weiß, zum Beißen", "твёрдый, белый, для кусания", "Hard, white, for biting", "koerper", 1],
  ["Herz", "Сердце", "heart", "pumpt Blut durch den Körper", "качает кровь по телу", "Pumps blood through the body", "koerper", 2],
  ["Gehirn", "Мозг", "brain", "denkt und steuert den Körper", "думает и управляет телом", "Thinks and controls the body", "koerper", 2],
  ["Lunge", "Лёгкие", "lungs", "damit atmen wir", "ими мы дышим", "We breathe with them", "koerper", 2],
  ["Magen", "Желудок", "stomach", "verdaut das Essen", "переваривает еду", "Digests food", "koerper", 2],
  ["Knochen", "Кость", "bone", "harte Teile im Körper", "твёрдые части тела", "Hard parts of the body", "koerper", 2],
  ["Muskel", "Мышца", "muscle", "macht uns stark, bewegt den Körper", "делает нас сильными, движет телом", "Makes us strong, moves the body", "koerper", 2],
  ["Blut", "Кровь", "blood", "rote Flüssigkeit im Körper", "красная жидкость в теле", "A red liquid in the body", "koerper", 2],
  ["Haut", "Кожа", "skin", "schützt unseren Körper außen", "защищает наше тело снаружи", "Protects our body on the outside", "koerper", 2],
  ["Rücken", "Спина", "back", "hintere Seite des Körpers", "задняя сторона тела", "The back side of the body", "koerper", 2],
  ["Schulter", "Плечо", "shoulder", "zwischen Hals und Arm", "между шеей и рукой", "Between neck and arm", "koerper", 2],
  ["Knie", "Колено", "knee", "Gelenk in der Mitte des Beins", "сустав в середине ноги", "A joint in the middle of the leg", "koerper", 2],
  ["Bauch", "Живот", "belly", "vorderer Teil des Körpers", "передняя часть тела", "The front part of the body", "koerper", 2],
  ["Hals", "Шея", "neck", "verbindet Kopf und Körper", "соединяет голову и тело", "Connects head and body", "koerper", 2],
  ["Zunge", "Язык", "tongue", "im Mund, schmeckt", "во рту, чувствует вкус", "In the mouth, tastes", "koerper", 2],
  ["Wange", "Щека", "cheek", "weiche Seite im Gesicht", "мягкая сторона лица", "A soft side of the face", "koerper", 2],
  ["Stirn", "Лоб", "forehead", "Teil des Gesichts über den Augen", "часть лица над глазами", "Part of the face above the eyes", "koerper", 2],
  ["Wimper", "Ресница", "eyelash", "kleines Haar am Auge", "маленький волосок у глаза", "A small hair at the eye", "koerper", 3],
  ["Daumen", "Большой палец", "thumb", "dicker Finger", "толстый палец", "The thick finger", "koerper", 3],

  // ── Alltag ─────────────────────────────────────────────────────────
  ["Haus", "Дом", "house", "Gebäude, in dem man wohnt", "здание, в котором живут", "A building where one lives", "alltag", 1],
  ["Tür", "Дверь", "door", "damit öffnet man das Haus", "ею открывают дом", "You open the house with it", "alltag", 1],
  ["Fenster", "Окно", "window", "Glas, durch das man schaut", "стекло, через которое смотрят", "Glass through which you look", "alltag", 1],
  ["Tisch", "Стол", "table", "Möbel zum Essen", "мебель для еды", "Furniture for eating", "alltag", 1],
  ["Stuhl", "Стул", "chair", "Möbel zum Sitzen", "мебель для сидения", "Furniture for sitting", "alltag", 1],
  ["Bett", "Кровать", "bed", "Möbel zum Schlafen", "мебель для сна", "Furniture for sleeping", "alltag", 1],
  ["Schrank", "Шкаф", "cupboard", "Möbel zum Aufbewahren", "мебель для хранения", "Furniture for storing things", "alltag", 1],
  ["Teller", "Тарелка", "plate", "darauf liegt das Essen", "на ней лежит еда", "Food lies on it", "alltag", 1],
  ["Tasse", "Чашка", "cup", "daraus trinkt man", "из неё пьют", "You drink from it", "alltag", 1],
  ["Löffel", "Ложка", "spoon", "Besteck zum Suppe essen", "прибор для супа", "Cutlery for eating soup", "alltag", 1],
  ["Messer", "Нож", "knife", "Besteck zum Schneiden", "прибор для резки", "Cutlery for cutting", "alltag", 1],
  ["Gabel", "Вилка", "fork", "Besteck mit Zinken", "прибор с зубцами", "Cutlery with prongs", "alltag", 1],
  ["Brot", "Хлеб", "bread", "gebackenes Nahrungsmittel", "печёный продукт", "A baked food", "alltag", 1],
  ["Milch", "Молоко", "milk", "weißes Getränk von der Kuh", "белый напиток от коровы", "A white drink from the cow", "alltag", 1],
  ["Wasser", "Вода", "water", "Getränk, das Leben braucht", "напиток, нужный для жизни", "A drink that life needs", "alltag", 1],
  ["Apfel", "Яблоко", "apple", "rundes Obst, rot oder grün", "круглый фрукт, красный или зелёный", "A round fruit, red or green", "alltag", 1],
  ["Buch", "Книга", "book", "hat Seiten zum Lesen", "имеет страницы для чтения", "Has pages for reading", "alltag", 1],
  ["Stift", "Ручка", "pen", "damit schreibt man", "ею пишут", "You write with it", "alltag", 1],
  ["Papier", "Бумага", "paper", "dünnes Blatt zum Schreiben", "тонкий лист для письма", "A thin sheet for writing", "alltag", 1],
  ["Schule", "Школа", "school", "Haus, wo man lernt", "здание, где учатся", "A building where you learn", "alltag", 1],
  ["Uhr", "Часы", "clock", "zeigt die Zeit", "показывает время", "Shows the time", "alltag", 1],
  ["Lampe", "Лампа", "lamp", "macht Licht", "даёт свет", "Makes light", "alltag", 1],
  ["Schlüssel", "Ключ", "key", "öffnet die Tür", "открывает дверь", "Opens the door", "alltag", 1],
  ["Treppe", "Лестница", "stairs", "Stufen nach oben", "ступени вверх", "Steps upward", "alltag", 1],
  ["Dach", "Крыша", "roof", "oben auf dem Haus", "сверху дома", "On top of the house", "alltag", 2],
  ["Keller", "Подвал", "cellar", "Raum unter dem Haus", "помещение под домом", "A room under the house", "alltag", 2],
  ["Spiegel", "Зеркало", "mirror", "darin sieht man sich", "в нём видят себя", "You see yourself in it", "alltag", 2],
  ["Kissen", "Подушка", "pillow", "weich, für den Kopf im Bett", "мягкая, для головы в кровати", "Soft, for the head in bed", "alltag", 2],
  ["Decke", "Одеяло", "blanket", "hält warm im Bett", "согревает в кровати", "Keeps you warm in bed", "alltag", 2],
  ["Vorhang", "Штора", "curtain", "Stoff vor dem Fenster", "ткань перед окном", "Fabric in front of the window", "alltag", 2],

  // ── Berufe ─────────────────────────────────────────────────────────
  ["Arzt", "Врач", "doctor", "hilft kranken Menschen", "помогает больным людям", "Helps sick people", "berufe", 2],
  ["Lehrer", "Учитель", "teacher", "bringt Kindern etwas bei", "учит детей", "Teaches children", "berufe", 2],
  ["Bäcker", "Пекарь", "baker", "backt Brot und Kuchen", "печёт хлеб и пироги", "Bakes bread and cakes", "berufe", 2],
  ["Koch", "Повар", "cook", "bereitet Essen zu", "готовит еду", "Prepares food", "berufe", 2],
  ["Bauer", "Фермер", "farmer", "arbeitet auf dem Feld", "работает в поле", "Works in the field", "berufe", 2],
  ["Polizist", "Полицейский", "police officer", "sorgt für Ordnung", "следит за порядком", "Keeps order", "berufe", 2],
  ["Feuerwehrmann", "Пожарный", "firefighter", "löscht Feuer", "тушит огонь", "Extinguishes fire", "berufe", 2],
  ["Pilot", "Пилот", "pilot", "fliegt Flugzeuge", "водит самолёты", "Flies planes", "berufe", 2],
  ["Busfahrer", "Водитель автобуса", "bus driver", "fährt den Bus", "водит автобус", "Drives the bus", "berufe", 2],
  ["Verkäufer", "Продавец", "shop assistant", "verkauft Waren", "продаёт товары", "Sells goods", "berufe", 2],
  ["Friseur", "Парикмахер", "hairdresser", "schneidet Haare", "стрижёт волосы", "Cuts hair", "berufe", 2],
  ["Schneider", "Портной", "tailor", "näht Kleidung", "шьёт одежду", "Sews clothes", "berufe", 2],
  ["Maler", "Маляр", "painter", "streicht Wände", "красит стены", "Paints walls", "berufe", 2],
  ["Musiker", "Музыкант", "musician", "macht Musik", "создаёт музыку", "Makes music", "berufe", 2],
  ["Sänger", "Певец", "singer", "singt Lieder", "поёт песни", "Sings songs", "berufe", 2],
  ["Tänzer", "Танцор", "dancer", "tanzt", "танцует", "Dances", "berufe", 2],
  ["Schriftsteller", "Писатель", "writer", "schreibt Geschichten", "пишет истории", "Writes stories", "berufe", 3],
  ["Künstler", "Художник", "artist", "schafft Kunst", "создаёт искусство", "Creates art", "berufe", 2],
  ["Fotograf", "Фотограф", "photographer", "macht Fotos", "делает фотографии", "Takes photos", "berufe", 2],
  ["Gärtner", "Садовник", "gardener", "pflegt Pflanzen", "ухаживает за растениями", "Cares for plants", "berufe", 2],
  ["Tischler", "Плотник", "carpenter", "baut Möbel aus Holz", "делает мебель из дерева", "Builds wooden furniture", "berufe", 2],
  ["Mechaniker", "Механик", "mechanic", "repariert Autos und Maschinen", "чинит автомобили и машины", "Repairs cars and machines", "berufe", 2],
  ["Elektriker", "Электрик", "electrician", "arbeitet mit Strom", "работает с электричеством", "Works with electricity", "berufe", 2],
  ["Zahnarzt", "Зубной врач", "dentist", "behandelt Zähne", "лечит зубы", "Treats teeth", "berufe", 2],
  ["Apotheker", "Аптекарь", "pharmacist", "gibt Medikamente", "выдаёт лекарства", "Gives medicines", "berufe", 3],
  ["Richter", "Судья", "judge", "entscheidet über Recht", "решает по закону", "Decides on law", "berufe", 3],
  ["Anwalt", "Адвокат", "lawyer", "vertritt Menschen vor Gericht", "защищает людей в суде", "Represents people in court", "berufe", 3],
  ["Architekt", "Архитектор", "architect", "plant Gebäude", "проектирует здания", "Plans buildings", "berufe", 3],
  ["Wissenschaftler", "Учёный", "scientist", "erforscht die Welt", "исследует мир", "Explores the world", "berufe", 3],
  ["Astronaut", "Космонавт", "astronaut", "fliegt ins Weltall", "летает в космос", "Flies into space", "berufe", 2],

  // ── Eigenschaften ──────────────────────────────────────────────────
  ["groß", "Большой", "big", "nicht klein", "не маленький", "Not small", "eigenschaften", 3],
  ["klein", "Маленький", "small", "nicht groß", "не большой", "Not big", "eigenschaften", 3],
  ["schnell", "Быстрый", "fast", "bewegt sich in kurzer Zeit", "движется за короткое время", "Moves in a short time", "eigenschaften", 3],
  ["langsam", "Медленный", "slow", "braucht viel Zeit", "требует много времени", "Needs a lot of time", "eigenschaften", 3],
  ["stark", "Сильный", "strong", "hat viel Kraft", "имеет много силы", "Has a lot of strength", "eigenschaften", 3],
  ["schwach", "Слабый", "weak", "hat wenig Kraft", "имеет мало силы", "Has little strength", "eigenschaften", 3],
  ["laut", "Громкий", "loud", "mit viel Geräusch", "с большим шумом", "With a lot of noise", "eigenschaften", 3],
  ["leise", "Тихий", "quiet", "fast ohne Geräusch", "почти без шума", "Almost without noise", "eigenschaften", 3],
  ["hell", "Светлый", "bright", "mit viel Licht", "со многим светом", "With a lot of light", "eigenschaften", 3],
  ["dunkel", "Тёмный", "dark", "ohne viel Licht", "без многого света", "Without much light", "eigenschaften", 3],
  ["warm", "Тёплый", "warm", "angenehm heiß", "приятно горячий", "Pleasantly hot", "eigenschaften", 3],
  ["kalt", "Холодный", "cold", "nicht warm", "не тёплый", "Not warm", "eigenschaften", 3],
  ["nass", "Мокрый", "wet", "voller Wasser", "полный воды", "Full of water", "eigenschaften", 3],
  ["trocken", "Сухой", "dry", "ohne Wasser", "без воды", "Without water", "eigenschaften", 3],
  ["glatt", "Гладкий", "smooth", "ohne Unebenheiten", "без неровностей", "Without bumps", "eigenschaften", 3],
  ["rau", "Шершавый", "rough", "uneben, nicht glatt", "неровный, не гладкий", "Uneven, not smooth", "eigenschaften", 3],
  ["schwer", "Тяжёлый", "heavy", "wiegt viel", "много весит", "Weighs a lot", "eigenschaften", 3],
  ["leicht", "Лёгкий", "light", "wiegt wenig", "мало весит", "Weighs little", "eigenschaften", 3],
  ["hart", "Твёрдый", "hard", "fest, nicht weich", "крепкий, не мягкий", "Firm, not soft", "eigenschaften", 3],
  ["weich", "Мягкий", "soft", "angenehm nachgiebig", "приятно податливый", "Pleasantly yielding", "eigenschaften", 3],
  ["scharf", "Острый", "sharp", "schneidet gut", "хорошо режет", "Cuts well", "eigenschaften", 3],
  ["stumpf", "Тупой", "blunt", "schneidet nicht gut", "плохо режет", "Does not cut well", "eigenschaften", 3],
  ["mutig", "Смелый", "brave", "ohne Angst", "без страха", "Without fear", "eigenschaften", 3],
  ["ängstlich", "Боязливый", "fearful", "voller Angst", "полный страха", "Full of fear", "eigenschaften", 3],
  ["freundlich", "Дружелюбный", "friendly", "nett zu anderen", "добрый к другим", "Kind to others", "eigenschaften", 3],
  ["fleißig", "Прилежный", "diligent", "arbeitet viel", "много работает", "Works a lot", "eigenschaften", 3],
  ["faul", "Ленивый", "lazy", "arbeitet ungern", "не любит работать", "Does not like to work", "eigenschaften", 3],
  ["klug", "Умный", "clever", "versteht schnell", "быстро понимает", "Understands quickly", "eigenschaften", 3],
  ["ehrlich", "Честный", "honest", "sagt die Wahrheit", "говорит правду", "Tells the truth", "eigenschaften", 3],
  ["neugierig", "Любопытный", "curious", "will alles wissen", "хочет всё знать", "Wants to know everything", "eigenschaften", 3],

  // ── Gefühle ────────────────────────────────────────────────────────
  ["Freude", "Радость", "joy", "Gefühl, wenn etwas Schönes passiert", "чувство, когда случается что-то хорошее", "A feeling when something nice happens", "gefuehle", 4],
  ["Trauer", "Печаль", "sadness", "Gefühl, wenn etwas Schlimmes passiert", "чувство, когда случается что-то плохое", "A feeling when something bad happens", "gefuehle", 4],
  ["Wut", "Гнев", "anger", "starkes Gefühl, wenn etwas ärgert", "сильное чувство, когда что-то злит", "A strong feeling when something annoys you", "gefuehle", 4],
  ["Angst", "Страх", "fear", "Gefühl bei Gefahr", "чувство при опасности", "A feeling in danger", "gefuehle", 4],
  ["Mut", "Смелость", "courage", "keine Angst haben", "не иметь страха", "Having no fear", "gefuehle", 4],
  ["Liebe", "Любовь", "love", "starkes Gefühl für jemanden", "сильное чувство к кому-то", "A strong feeling for someone", "gefuehle", 4],
  ["Hass", "Ненависть", "hatred", "sehr starkes negatives Gefühl", "очень сильное отрицательное чувство", "A very strong negative feeling", "gefuehle", 4],
  ["Neid", "Зависть", "envy", "man will, was andere haben", "хочется того, что есть у других", "Wanting what others have", "gefuehle", 4],
  ["Stolz", "Гордость", "pride", "zufrieden mit sich selbst", "доволен собой", "Pleased with oneself", "gefuehle", 4],
  ["Scham", "Стыд", "shame", "peinliches Gefühl", "неловкое чувство", "An embarrassing feeling", "gefuehle", 4],
  ["Hoffnung", "Надежда", "hope", "glauben, dass Gutes kommt", "вера, что придёт хорошее", "Believing that good will come", "gefuehle", 4],
  ["Verzweiflung", "Отчаяние", "despair", "keine Hoffnung mehr", "больше нет надежды", "No more hope", "gefuehle", 4],
  ["Glück", "Счастье", "happiness", "großes Wohlgefühl", "большое хорошее чувство", "A great good feeling", "gefuehle", 4],
  ["Unglück", "Несчастье", "misfortune", "Pech, schlechtes Gefühl", "невезение, плохое чувство", "Bad luck, a bad feeling", "gefuehle", 4],
  ["Zufriedenheit", "Удовлетворение", "contentment", "alles ist gut so", "всё хорошо", "Everything is fine", "gefuehle", 4],
  ["Langeweile", "Скука", "boredom", "nichts interessiert", "ничего не интересно", "Nothing is interesting", "gefuehle", 4],
  ["Neugier", "Любопытство", "curiosity", "etwas wissen wollen", "желание что-то узнать", "Wanting to know something", "gefuehle", 4],
  ["Überraschung", "Удивление", "surprise", "etwas Unerwartetes", "что-то неожиданное", "Something unexpected", "gefuehle", 4],
  ["Erleichterung", "Облегчение", "relief", "Sorge fällt ab", "забота уходит", "Worry falls away", "gefuehle", 4],
  ["Sorge", "Беспокойство", "worry", "Gedanken voller Angst", "мысли, полные страха", "Thoughts full of fear", "gefuehle", 4],
  ["Mitgefühl", "Сочувствие", "compassion", "mit anderen fühlen", "чувствовать вместе с другими", "Feeling with others", "gefuehle", 4],
  ["Eifersucht", "Ревность", "jealousy", "Angst, jemanden zu verlieren", "страх потерять кого-то", "Fear of losing someone", "gefuehle", 4],
  ["Dankbarkeit", "Благодарность", "gratitude", "froh über etwas sein", "радоваться чему-то", "Being glad about something", "gefuehle", 4],
  ["Einsamkeit", "Одиночество", "loneliness", "allein sein", "быть одному", "Being alone", "gefuehle", 4],
  ["Sehnsucht", "Тоска", "longing", "starker Wunsch nach jemandem", "сильное желание по кому-то", "A strong wish for someone", "gefuehle", 4],
  ["Müdigkeit", "Усталость", "tiredness", "Gefühl, schlafen zu wollen", "чувство, что хочется спать", "A feeling of wanting to sleep", "gefuehle", 4],
  ["Aufregung", "Волнение", "excitement", "aufgeregt vor etwas", "взволнован перед чем-то", "Excited before something", "gefuehle", 4],
  ["Ruhe", "Спокойствие", "calm", "friedliches Gefühl", "мирное чувство", "A peaceful feeling", "gefuehle", 4],
  ["Unsicherheit", "Неуверенность", "uncertainty", "nicht wissen, was richtig ist", "не знать, что правильно", "Not knowing what is right", "gefuehle", 4],
  ["Vertrauen", "Доверие", "trust", "sicher sein, dass jemand hilft", "уверенность, что кто-то поможет", "Being sure that someone helps", "gefuehle", 4],

  // ── Zeit & Raum ────────────────────────────────────────────────────
  ["Minute", "Минута", "minute", "60 Sekunden", "60 секунд", "60 seconds", "zeit", 3],
  ["Stunde", "Час", "hour", "60 Minuten", "60 минут", "60 minutes", "zeit", 3],
  ["Tag", "День", "day", "24 Stunden", "24 часа", "24 hours", "zeit", 3],
  ["Woche", "Неделя", "week", "7 Tage", "7 дней", "7 days", "zeit", 3],
  ["Monat", "Месяц", "month", "etwa 30 Tage", "около 30 дней", "About 30 days", "zeit", 3],
  ["Jahr", "Год", "year", "12 Monate", "12 месяцев", "12 months", "zeit", 3],
  ["Morgen", "Утро", "morning", "Beginn des Tages", "начало дня", "The start of the day", "zeit", 3],
  ["Mittag", "Полдень", "noon", "Mitte des Tages", "середина дня", "The middle of the day", "zeit", 3],
  ["Abend", "Вечер", "evening", "Ende des Tages", "конец дня", "The end of the day", "zeit", 3],
  ["Nacht", "Ночь", "night", "Zeit zum Schlafen, dunkel", "время для сна, темно", "Time to sleep, dark", "zeit", 3],
  ["heute", "Сегодня", "today", "dieser Tag", "этот день", "This day", "zeit", 3],
  ["morgen", "Завтра", "tomorrow", "der nächste Tag", "следующий день", "The next day", "zeit", 3],
  ["gestern", "Вчера", "yesterday", "der Tag davor", "предыдущий день", "The day before", "zeit", 3],
  ["jetzt", "Сейчас", "now", "in diesem Moment", "в этот момент", "In this moment", "zeit", 3],
  ["früher", "Раньше", "earlier", "vor langer Zeit", "давно", "Long ago", "zeit", 3],
  ["später", "Позже", "later", "nach einiger Zeit", "через некоторое время", "After some time", "zeit", 3],
  ["bald", "Скоро", "soon", "in kurzer Zeit", "в короткое время", "In a short time", "zeit", 3],
  ["Vergangenheit", "Прошлое", "past", "Zeit, die schon war", "время, которое уже было", "Time that has been", "zeit", 4],
  ["Gegenwart", "Настоящее", "present", "Zeit, die jetzt ist", "время, которое сейчас", "Time that is now", "zeit", 4],
  ["Zukunft", "Будущее", "future", "Zeit, die kommt", "время, которое придёт", "Time to come", "zeit", 4],
  ["Anfang", "Начало", "beginning", "der erste Punkt", "первая точка", "The first point", "zeit", 4],
  ["Ende", "Конец", "end", "der letzte Punkt", "последняя точка", "The last point", "zeit", 4],
  ["Dauer", "Длительность", "duration", "wie lange etwas dauert", "как долго что-то длится", "How long something lasts", "zeit", 4],
  ["Moment", "Момент", "moment", "sehr kurze Zeit", "очень короткое время", "A very short time", "zeit", 4],
  ["Ewigkeit", "Вечность", "eternity", "unendliche Zeit", "бесконечное время", "Endless time", "zeit", 4],
  ["Frühling", "Весна", "spring", "Jahreszeit, alles blüht", "время года, всё цветёт", "Season when everything blooms", "zeit", 3],
  ["Sommer", "Лето", "summer", "heißeste Jahreszeit", "самое жаркое время года", "The hottest season", "zeit", 3],
  ["Herbst", "Осень", "autumn", "Jahreszeit, Blätter fallen", "время года, падают листья", "Season when leaves fall", "zeit", 3],
  ["Winter", "Зима", "winter", "kälteste Jahreszeit", "самое холодное время года", "The coldest season", "zeit", 3],
  ["Kalender", "Календарь", "calendar", "zeigt Tage und Monate", "показывает дни и месяцы", "Shows days and months", "zeit", 3],

  // ── Handlungen ─────────────────────────────────────────────────────
  ["laufen", "Бежать", "run", "sich schnell auf Füßen bewegen", "быстро двигаться на ногах", "To move quickly on feet", "handlungen", 3],
  ["springen", "Прыгать", "jump", "sich in die Luft stoßen", "отталкиваться в воздух", "To push oneself into the air", "handlungen", 3],
  ["lesen", "Читать", "read", "Schrift verstehen", "понимать написанное", "To understand writing", "handlungen", 3],
  ["schreiben", "Писать", "write", "Wörter mit Stift machen", "делать слова ручкой", "To make words with a pen", "handlungen", 3],
  ["essen", "Есть", "eat", "Nahrung in den Mund nehmen", "брать еду в рот", "To take food into the mouth", "handlungen", 3],
  ["trinken", "Пить", "drink", "Flüssigkeit in den Mund nehmen", "брать жидкость в рот", "To take liquid into the mouth", "handlungen", 3],
  ["schlafen", "Спать", "sleep", "mit geschlossenen Augen ruhen", "отдыхать с закрытыми глазами", "To rest with closed eyes", "handlungen", 3],
  ["sprechen", "Говорить", "speak", "Wörter sagen", "произносить слова", "To say words", "handlungen", 3],
  ["singen", "Петь", "sing", "mit der Stimme Musik machen", "делать музыку голосом", "To make music with the voice", "handlungen", 3],
  ["malen", "Рисовать", "paint", "mit Farben Bilder machen", "делать картины красками", "To make pictures with colours", "handlungen", 3],
  ["bauen", "Строить", "build", "etwas zusammenfügen", "соединять что-то", "To put something together", "handlungen", 3],
  ["werfen", "Бросать", "throw", "etwas durch die Luft schleudern", "кидать что-то по воздуху", "To hurl something through the air", "handlungen", 3],
  ["fangen", "Ловить", "catch", "etwas in der Luft greifen", "хватать что-то в воздухе", "To grab something in the air", "handlungen", 3],
  ["ziehen", "Тянуть", "pull", "etwas zu sich her bewegen", "двигать что-то к себе", "To move something toward oneself", "handlungen", 3],
  ["schieben", "Толкать", "push", "etwas von sich weg bewegen", "двигать что-то от себя", "To move something away from oneself", "handlungen", 3],
  ["öffnen", "Открывать", "open", "aufmachen", "открывать", "To open up", "handlungen", 3],
  ["schließen", "Закрывать", "close", "zumachen", "закрывать", "To shut", "handlungen", 3],
  ["lachen", "Смеяться", "laugh", "Freude mit Lauten zeigen", "показывать радость звуками", "To show joy with sounds", "handlungen", 3],
  ["weinen", "Плакать", "cry", "Tränen aus Trauer", "слёзы от печали", "Tears from sadness", "handlungen", 3],
  ["denken", "Думать", "think", "im Kopf überlegen", "размышлять в голове", "To ponder in the head", "handlungen", 3],
  ["lernen", "Учить", "learn", "Neues verstehen und behalten", "понимать и запоминать новое", "To understand and keep new things", "handlungen", 3],
  ["vergessen", "Забывать", "forget", "nicht mehr erinnern", "больше не помнить", "To no longer remember", "handlungen", 3],
  ["erinnern", "Вспоминать", "remember", "wieder im Kopf haben", "снова иметь в голове", "To have in the head again", "handlungen", 3],
  ["helfen", "Помогать", "help", "jemandem Unterstützung geben", "давать кому-то поддержку", "To give someone support", "handlungen", 3],
  ["teilen", "Делиться", "share", "etwas mit anderen benutzen", "пользоваться чем-то вместе с другими", "To use something with others", "handlungen", 3],
  ["warten", "Ждать", "wait", "Zeit vergehen lassen, bis etwas kommt", "ждать, пока что-то придёт", "To let time pass until something comes", "handlungen", 3],
  ["suchen", "Искать", "search", "etwas finden wollen", "хотеть найти что-то", "To want to find something", "handlungen", 3],
  ["finden", "Находить", "find", "etwas entdecken", "обнаруживать что-то", "To discover something", "handlungen", 3],
  ["kochen", "Готовить", "cook", "Essen zubereiten", "готовить еду", "To prepare food", "handlungen", 3],
  ["reisen", "Путешествовать", "travel", "in ferne Orte fahren", "ездить в далёкие места", "To go to far places", "handlungen", 3],

  // ── Bildhafte Wörter & Redewendungen ──────────────────────────────
  ["Herz aus Gold", "Золотое сердце", "heart of gold", "sehr gütiger Mensch", "очень добрый человек", "A very kind person", "bildhaft", 5],
  ["Butter bei die Fische", "Говорить прямо", "get to the point", "klar und ehrlich werden", "говорить ясно и честно", "To become clear and honest", "bildhaft", 5],
  ["den Kopf verlieren", "Терять голову", "lose one's head", "in Panik geraten", "впадать в панику", "To get into a panic", "bildhaft", 5],
  ["ins Gras beißen", "Протянуть ноги", "bite the dust", "sterben (umgangssprachlich)", "умереть (разговорное)", "To die (colloquial)", "bildhaft", 5],
  ["jemandem die Daumen drücken", "Держать кулаки", "keep one's fingers crossed", "Glück wünschen", "желать удачи", "To wish luck", "bildhaft", 5],
  ["die Nase voll haben", "Быть сытым по горло", "have had enough", "genug haben von etwas", "устать от чего-то", "To be fed up with something", "bildhaft", 5],
  ["ein Auge zudrücken", "Смотреть сквозь пальцы", "turn a blind eye", "etwas nachsichtig übersehen", "снисходительно не замечать", "To overlook something leniently", "bildhaft", 5],
  ["auf Wolke sieben", "На седьмом небе", "on cloud nine", "sehr verliebt sein", "быть очень влюблённым", "To be very much in love", "bildhaft", 5],
  ["kalte Füße bekommen", "Струсить", "get cold feet", "Angst bekommen", "испугаться", "To become afraid", "bildhaft", 5],
  ["ein Buch mit sieben Siegeln", "Книга за семью печатями", "a closed book", "etwas Unverständliches", "что-то непонятное", "Something incomprehensible", "bildhaft", 5],
  ["das Eis brechen", "Разбить лёд", "break the ice", "eine angespannte Lage lösen", "разрядить напряжённую обстановку", "To ease a tense situation", "bildhaft", 5],
  ["jemandem auf den Zahn fühlen", "Прощупывать кого-то", "pump someone for information", "genau ausfragen", "подробно расспрашивать", "To question thoroughly", "bildhaft", 5],
  ["die Katze aus dem Sack lassen", "Выпустить кота из мешка", "let the cat out of the bag", "ein Geheimnis verraten", "выдать тайну", "To reveal a secret", "bildhaft", 5],
  ["ins Fettnäpfchen treten", "Сесть в лужу", "put one's foot in it", "etwas Peinliches tun oder sagen", "сделать или сказать что-то неловкое", "To do or say something embarrassing", "bildhaft", 5],
  ["den roten Faden verlieren", "Потерять нить", "lose the thread", "nicht mehr wissen, worum es geht", "перестать понимать, о чём речь", "To no longer know what it is about", "bildhaft", 5],
  ["die Zeit totschlagen", "Убивать время", "kill time", "warten, sich langweilen", "ждать и скучать", "To wait and be bored", "bildhaft", 5],
  ["alles in einen Topf werfen", "Валить всё в одну кучу", "lump together", "Dinge unzulässig vermischen", "недопустимо смешивать вещи", "To mix things up inadmissibly", "bildhaft", 5],
  ["im siebten Himmel sein", "Быть на седьмом небе", "be in seventh heaven", "überglücklich sein", "быть очень счастливым", "To be overjoyed", "bildhaft", 5],
  ["das Handtuch werfen", "Бросить полотенце", "throw in the towel", "aufgeben", "сдаваться", "To give up", "bildhaft", 5],
  ["sich zusammenreißen", "Взять себя в руки", "pull oneself together", "sich beherrschen", "держать себя в руках", "To control oneself", "bildhaft", 5],
  ["den Faden verlieren", "Потерять нить разговора", "lose one's train of thought", "den Gedanken unterbrechen", "потерять мысль", "To lose one's thought", "bildhaft", 5],
  ["aus dem Rahmen fallen", "Выбиваться из ряда", "be out of the ordinary", "anders als üblich sein", "быть необычным", "To be different from usual", "bildhaft", 5],
  ["ein Gedächtnis wie ein Sieb", "Дырявая память", "memory like a sieve", "schnell vergessen", "быстро забывать", "To forget quickly", "bildhaft", 5],
  ["leere Worte", "Пустые слова", "empty words", "Versprechen ohne Taten", "обещания без дел", "Promises without deeds", "bildhaft", 5],
  ["den Mund halten", "Держать язык за зубами", "keep one's mouth shut", "still sein", "молчать", "To be quiet", "bildhaft", 5],
  ["jemandem die Stirn bieten", "Давать отпор", "stand up to someone", "sich widersetzen", "сопротивляться", "To resist", "bildhaft", 5],
  ["ein Himmelfahrtskommando", "Смертельный номер", "suicide mission", "gefährliche, sinnlose Aufgabe", "опасное, бессмысленное задание", "A dangerous, pointless task", "bildhaft", 5],
  ["kein Blatt vor den Mund nehmen", "Говорить без обиняков", "not mince words", "direkt sagen", "говорить прямо", "To say directly", "bildhaft", 5],
  ["sich in die Haare kriegen", "Вцепиться друг в друга", "get into a fight", "streiten", "ссориться", "To quarrel", "bildhaft", 5],
  ["von der Hand in den Mund leben", "Жить от зарплаты до зарплаты", "live hand to mouth", "ohne Ersparnisse leben", "жить без сбережений", "To live without savings", "bildhaft", 5],
];

/** Kategorien (Gebiete) – für spätere Filterung/Anzeige. */
export const KATEGORIEN = {
  natur: { de: "Natur", ru: "Природа", en: "Nature" },
  tiere: { de: "Tiere", ru: "Животные", en: "Animals" },
  koerper: { de: "Körper", ru: "Тело", en: "Body" },
  alltag: { de: "Alltag", ru: "Быт", en: "Daily life" },
  berufe: { de: "Berufe", ru: "Профессии", en: "Professions" },
  eigenschaften: { de: "Eigenschaften", ru: "Свойства", en: "Properties" },
  gefuehle: { de: "Gefühle", ru: "Чувства", en: "Feelings" },
  zeit: { de: "Zeit & Raum", ru: "Время и пространство", en: "Time & space" },
  handlungen: { de: "Handlungen", ru: "Действия", en: "Actions" },
  bildhaft: { de: "Bildhaft", ru: "Образные слова", en: "Figurative" },
};
